/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pyxis.calltech.swing.telas;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JPanel;
import oshi.SystemInfo;
import oshi.hardware.HardwareAbstractionLayer;

public class CalltechGui extends javax.swing.JFrame {
    
    GridBagLayout layout = new GridBagLayout();

    private JPanel jpVisaoGeral;
    private JPanel jpCpu;
    private JPanel jpMemoria;
    private JPanel jpDisco;
    private JPanel jpRede;
    
    private SystemInfo systemInfo;
    private HardwareAbstractionLayer hardwareAbstractionLayer;

    /**
     * Creates new form CalltechGui
     */
    public CalltechGui() {
        initComponents();   
        this.setLocationRelativeTo(null);
        
        this.systemInfo = new SystemInfo();
        this.hardwareAbstractionLayer = systemInfo.getHardware();
        
        this.jpVisaoGeral = new jpVisaoGeral(hardwareAbstractionLayer);
        this.jpCpu = new jpCpu();
        this.jpMemoria = new jpMemoria();
        this.jpDisco = new jpDisco();
        this.jpRede = new jpRede();
        
        jpContent.setLayout(layout);
        
        GridBagConstraints gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        
        jpContent.add(jpVisaoGeral, gridBagConstraints);
        jpContent.add(jpCpu, gridBagConstraints);
        jpContent.add(jpMemoria, gridBagConstraints);
        jpContent.add(jpDisco, gridBagConstraints);
        jpContent.add(jpRede, gridBagConstraints);

        
        jpVisaoGeral.setVisible(true);
        jpCpu.setVisible(false);
        jpMemoria.setVisible(false);
        jpDisco.setVisible(false);
        jpRede.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jpParent = new javax.swing.JPanel();
        jpSide = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_visao = new javax.swing.JPanel();
        ind_geral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_cpu = new javax.swing.JPanel();
        ind_cpu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_memoria = new javax.swing.JPanel();
        ind_memoria = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_disco = new javax.swing.JPanel();
        ind_disco = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_rede = new javax.swing.JPanel();
        ind_rede = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpContent = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CallTech");

        jpParent.setForeground(new java.awt.Color(250, 250, 250));

        jpSide.setBackground(new java.awt.Color(94, 114, 228));

        jLabel2.setFont(new java.awt.Font("Bariol Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("CallTech");

        jLabel3.setFont(new java.awt.Font("Bariol Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("monitoramento de máquinas");

        btn_visao.setBackground(new java.awt.Color(114, 134, 248));
        btn_visao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_visaoMousePressed(evt);
            }
        });
        btn_visao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout ind_geralLayout = new javax.swing.GroupLayout(ind_geral);
        ind_geral.setLayout(ind_geralLayout);
        ind_geralLayout.setHorizontalGroup(
            ind_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_geralLayout.setVerticalGroup(
            ind_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_visao.add(ind_geral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, -1));

        jLabel1.setFont(new java.awt.Font("Bariol Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("Visão geral");
        btn_visao.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 9, -1, -1));

        btn_cpu.setBackground(new java.awt.Color(94, 114, 228));
        btn_cpu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_cpuMousePressed(evt);
            }
        });
        btn_cpu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_cpu.setOpaque(false);

        javax.swing.GroupLayout ind_cpuLayout = new javax.swing.GroupLayout(ind_cpu);
        ind_cpu.setLayout(ind_cpuLayout);
        ind_cpuLayout.setHorizontalGroup(
            ind_cpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_cpuLayout.setVerticalGroup(
            ind_cpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_cpu.add(ind_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, -1));

        jLabel4.setFont(new java.awt.Font("Bariol Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("Informações de CPU");
        btn_cpu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 9, -1, -1));

        btn_memoria.setBackground(new java.awt.Color(94, 114, 228));
        btn_memoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_memoriaMousePressed(evt);
            }
        });
        btn_memoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_memoria.setOpaque(false);

        javax.swing.GroupLayout ind_memoriaLayout = new javax.swing.GroupLayout(ind_memoria);
        ind_memoria.setLayout(ind_memoriaLayout);
        ind_memoriaLayout.setHorizontalGroup(
            ind_memoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_memoriaLayout.setVerticalGroup(
            ind_memoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_memoria.add(ind_memoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, -1));

        jLabel5.setFont(new java.awt.Font("Bariol Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 250, 250));
        jLabel5.setText("Informações de Memósria");
        btn_memoria.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 9, -1, -1));

        btn_disco.setBackground(new java.awt.Color(94, 114, 228));
        btn_disco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_discoMousePressed(evt);
            }
        });
        btn_disco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_disco.setOpaque(false);

        javax.swing.GroupLayout ind_discoLayout = new javax.swing.GroupLayout(ind_disco);
        ind_disco.setLayout(ind_discoLayout);
        ind_discoLayout.setHorizontalGroup(
            ind_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_discoLayout.setVerticalGroup(
            ind_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_disco.add(ind_disco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, -1));

        jLabel6.setFont(new java.awt.Font("Bariol Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(250, 250, 250));
        jLabel6.setText("Informações de Disco");
        btn_disco.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 9, -1, -1));

        btn_rede.setBackground(new java.awt.Color(94, 114, 228));
        btn_rede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_redeMousePressed(evt);
            }
        });
        btn_rede.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_rede.setOpaque(false);

        javax.swing.GroupLayout ind_redeLayout = new javax.swing.GroupLayout(ind_rede);
        ind_rede.setLayout(ind_redeLayout);
        ind_redeLayout.setHorizontalGroup(
            ind_redeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_redeLayout.setVerticalGroup(
            ind_redeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_rede.add(ind_rede, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, -1));

        jLabel7.setFont(new java.awt.Font("Bariol Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(250, 250, 250));
        jLabel7.setText("Informações de Rede");
        btn_rede.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 9, -1, -1));

        javax.swing.GroupLayout jpSideLayout = new javax.swing.GroupLayout(jpSide);
        jpSide.setLayout(jpSideLayout);
        jpSideLayout.setHorizontalGroup(
            jpSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_visao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_cpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_memoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_disco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_rede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpSideLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jpSideLayout.setVerticalGroup(
            jpSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSideLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(btn_visao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_memoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_rede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpContentLayout = new javax.swing.GroupLayout(jpContent);
        jpContent.setLayout(jpContentLayout);
        jpContentLayout.setHorizontalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        jpContentLayout.setVerticalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpParentLayout = new javax.swing.GroupLayout(jpParent);
        jpParent.setLayout(jpParentLayout);
        jpParentLayout.setHorizontalGroup(
            jpParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpParentLayout.createSequentialGroup()
                .addComponent(jpSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpParentLayout.setVerticalGroup(
            jpParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpParentLayout.createSequentialGroup()
                .addComponent(jpContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_redeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_redeMousePressed
        resetColor(btn_visao);
        resetColor(btn_cpu);
        resetColor(btn_disco);
        resetColor(btn_memoria);
        setColor(btn_rede);
        
        ind_geral.setOpaque(false);
        ind_cpu.setOpaque(false);
        ind_disco.setOpaque(false);
        ind_memoria.setOpaque(false);
        ind_rede.setOpaque(true);
        
        jpVisaoGeral.setVisible(false);
        jpCpu.setVisible(false);
        jpMemoria.setVisible(false);
        jpDisco.setVisible(false);
        jpRede.setVisible(true);
    }//GEN-LAST:event_btn_redeMousePressed

    private void btn_discoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_discoMousePressed
        resetColor(btn_visao);
        resetColor(btn_cpu);
        setColor(btn_disco);
        resetColor(btn_memoria);
        resetColor(btn_rede);
        
        ind_geral.setOpaque(true);
        ind_cpu.setOpaque(false);
        ind_disco.setOpaque(true);
        ind_memoria.setOpaque(false);
        ind_rede.setOpaque(false);
        
        jpVisaoGeral.setVisible(false);
        jpCpu.setVisible(false);
        jpMemoria.setVisible(false);
        jpDisco.setVisible(true);
        jpRede.setVisible(false);
        
    }//GEN-LAST:event_btn_discoMousePressed

    private void btn_memoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memoriaMousePressed
        resetColor(btn_visao);
        resetColor(btn_cpu);
        resetColor(btn_disco);
        setColor(btn_memoria);
        resetColor(btn_rede);
        
        ind_geral.setOpaque(false);
        ind_cpu.setOpaque(false);
        ind_disco.setOpaque(false);
        ind_memoria.setOpaque(true);
        ind_rede.setOpaque(false);
        
        jpVisaoGeral.setVisible(false);
        jpCpu.setVisible(false);
        jpMemoria.setVisible(true);
        jpDisco.setVisible(false);
        jpRede.setVisible(false);
    }//GEN-LAST:event_btn_memoriaMousePressed

    private void btn_cpuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cpuMousePressed
        resetColor(btn_visao);
        setColor(btn_cpu);
        resetColor(btn_disco);
        resetColor(btn_memoria);
        resetColor(btn_rede);
        
        ind_geral.setOpaque(false);
        ind_cpu.setOpaque(true);
        ind_disco.setOpaque(false);
        ind_memoria.setOpaque(false);
        ind_rede.setOpaque(false);

        jpVisaoGeral.setVisible(false);
        jpCpu.setVisible(true);
        jpMemoria.setVisible(false);
        jpDisco.setVisible(false);
        jpRede.setVisible(false);
    }//GEN-LAST:event_btn_cpuMousePressed

    private void btn_visaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visaoMousePressed
        setColor(btn_visao);
        resetColor(btn_cpu);
        resetColor(btn_disco);
        resetColor(btn_memoria);
        resetColor(btn_rede);
        
        ind_geral.setOpaque(true);
        ind_cpu.setOpaque(false);
        ind_disco.setOpaque(false);
        ind_memoria.setOpaque(false);
        ind_rede.setOpaque(false);

        jpVisaoGeral.setVisible(true);
        jpCpu.setVisible(false);
        jpMemoria.setVisible(false);
        jpDisco.setVisible(false);
        jpRede.setVisible(false);
    }//GEN-LAST:event_btn_visaoMousePressed

    //set and reset color
     public void setColor(JPanel panel) {
        panel.setBackground(new Color(114,134,248));
    }
    
    public void resetColor(JPanel panel) {
        panel.setBackground(new Color(94,114,228));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalltechGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalltechGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalltechGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalltechGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        System.setProperty("file.encoding","UTF-8");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalltechGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_cpu;
    private javax.swing.JPanel btn_disco;
    private javax.swing.JPanel btn_memoria;
    private javax.swing.JPanel btn_rede;
    private javax.swing.JPanel btn_visao;
    private javax.swing.JPanel ind_cpu;
    private javax.swing.JPanel ind_disco;
    private javax.swing.JPanel ind_geral;
    private javax.swing.JPanel ind_memoria;
    private javax.swing.JPanel ind_rede;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jpContent;
    private javax.swing.JPanel jpParent;
    private javax.swing.JPanel jpSide;
    // End of variables declaration//GEN-END:variables
}
